Task 1. Pull request
brstu/TMAU-2023 pull request #1
Opened 2023-09-23 12:04 UTC by dzibukalexander

2023-09-24 21:34 UTC, ryzzax21 approved these changes
👍🤙🚬

2023-09-25 14:21 UTC, Endorvey approved these changes
Хорош

2023-09-28 16:04 UTC, Potseluiko-Misha commented
useful changes

2023-09-29 06:24 UTC, idzm requested changes

2023-09-29 06:24 UTC, idzm commented on .github/pr-title-checker-config.json
Данный файл не должен изменяться.

2023-09-29 06:24 UTC, idzm commented on .github/workflows/check_duplication.yml
Данный файл не должен изменяться.

2023-09-29 06:24 UTC, idzm commented on .github/workflows/pr-title-checker.yml
Данный файл не должен изменяться.

2023-09-29 06:24 UTC, idzm commented on .gitignore
Данный файл не должен изменяться. Изменения данного файла надо делать отдельным запросом, так как данный файл содержит глобальные настройки.

2023-10-02 09:23 UTC, idzm approved these changes

2023-10-02 09:23 UTC, merged