[task_01] Add solution.
brstu/TMAU-2023 pull request #12
Opened 2023-09-29 08:22 UTC by ryzzax21

2023-09-29 08:49 UTC, Endorvey approved these changes
Approved

2023-09-29 08:53 UTC, Aveerr approved these changes
Approved

2023-10-02 09:40 UTC, idzm approved these changes

2023-10-09 10:18 UTC, idzm requested changes
Необходимо добавить факт выполнения задания в общий файл - https://github.com/brstu/TMAU-2023/edit/main/readme.md#L29-29.

2023-10-13 05:24 UTC, idzm approved these changes

2023-10-13 05:24 UTC, merged