Fork
brstu/TMAU-2023 pull request #13
Opened 2023-09-29 08:27 UTC by Aveerr

2023-09-29 08:52 UTC, Endorvey approved these changes
Vozmoshno on ne 0% dublicated

2023-10-09 10:23 UTC, idzm requested changes
Файлы находятся не в требуемом каталоге - должны быть в `trunk/as00061xx/task_01`.

2023-10-13 05:34 UTC, idzm requested changes
Файлы в других каталогах не должны изменяться.

2023-10-13 11:54 UTC, idzm approved these changes

2023-10-13 11:55 UTC, merged