f
brstu/TMAU-2023 pull request #14
Opened 2023-09-29 08:29 UTC by Endorvey

f

2023-09-29 09:01 UTC, DopplerCore commented
Согласен, всё хорошо, что хорошо

2023-09-29 09:04 UTC, DopplerCore approved these changes
Сделано на совесть

2023-09-29 09:06 UTC, Aveerr approved these changes
Approved

2023-10-02 09:44 UTC, idzm requested changes
Необходимо удалить ненужные (бинарные и т.п.) файлы из данного запроса.

2023-10-03 18:35 UTC, Linkevich-Polina commented on trunk/as006110/task_01/doc/readme.md.txt
Лишнее расширение .txt

2023-10-03 18:37 UTC, Linkevich-Polina commented on trunk/as006110/task_01/src/Lab1/Lab1.cpp
cpp файл должен быть в папке src, папка Lab1 лишняя

2023-10-13 08:02 UTC, Endorvey commented on trunk/as006110/task_01/src/Lab1/Lab1.cpp
понял, извините, больше не повторится(там такого даже не было)

2023-10-13 08:10 UTC, Aveerr commented
Код просто пушечка

2023-10-13 11:53 UTC, idzm approved these changes

2023-10-13 11:53 UTC, merged