Marina as61
brstu/TMAU-2023 pull request #28
Opened 2023-10-05 20:46 UTC by marla124

2023-10-05 20:55 UTC, Linkevich-Polina commented
Все хорошо, но можно было использовать "using namespace std", чтобы  не прописывать постоянно "std::".

2023-10-06 15:08 UTC, Linkevich-Polina approved these changes
.

2023-10-09 10:31 UTC, idzm requested changes
Также добавить факт выполнения задания в общий файл - https://github.com/brstu/TMAU-2023/edit/main/readme.md#L17-17.

2023-10-10 12:17 UTC, Aurora-hwan commented
Вау! Это просто невероятно, код мега-хорош!

2023-10-11 04:38 UTC, Aurora-hwan commented
О мой бог, это просто невероятный код

2023-10-19 06:08 UTC, idzm approved these changes

2023-10-19 06:09 UTC, merged