Lab1_Sedko
brstu/TMAU-2023 pull request #4
Opened 2023-09-25 22:04 UTC by DopplerCore

Write

2023-09-26 05:25 UTC, Endorvey approved these changes
УльтраМегаХорош

2023-09-29 08:53 UTC, Asya2003 commented
Хорош

2023-09-29 09:05 UTC, Asya2003 approved these changes
Маладец

2023-09-29 09:20 UTC, Endorvey approved these changes
Соло зарешал, катку вытянул

2023-09-29 10:00 UTC, ryzzax21 approved these changes
🤨

2023-09-30 07:51 UTC, wasilenkai requested changes

2023-09-30 07:51 UTC, wasilenkai commented on trunk/as0006116/task_01/src/main.cpp
Ошибка C2084 функция "int main(void)" уже имеет текст реализации (2 функции main).

2023-09-30 07:51 UTC, wasilenkai commented on trunk/as0006116/task_01/src/main.cpp
> +}
Нужно удалить эту часть.
```suggestion
```

2023-10-02 09:33 UTC, idzm requested changes
Необходимо оставить одну реализацию "int main(void)".

2023-10-03 14:04 UTC, idzm approved these changes

2023-10-03 14:04 UTC, merged

2023-10-03 15:53 UTC, wasilenkai reviewed
Аll is well