Solution
brstu/TMAU-2023 pull request #7
Opened 2023-09-28 11:59 UTC by Asya2003

2023-09-29 05:04 UTC, sunset-ccc commented
Супер

2023-09-29 08:50 UTC, DopplerCore commented
Адинокий адинокий адиночка.

2023-09-29 09:06 UTC, DopplerCore approved these changes
Маладец

2023-09-29 09:12 UTC, Asya2003 reviewed
Сам себя не похвалишь- никто не похвалит Ауф

2023-10-02 09:39 UTC, idzm requested changes
Отсутствует файл описания сборки "CMakeLists.txt".

2023-10-09 10:13 UTC, idzm approved these changes

2023-10-09 10:14 UTC, merged