[task_01] pull request
brstu/TMAU-2023 pull request #8
Opened 2023-09-28 15:58 UTC by Potseluiko-Misha

2023-10-02 09:39 UTC, idzm requested changes
Отсутствует файл описания сборки "CMakeLists.txt".

2023-10-08 18:27 UTC, marla124 commented
напиши Pull с большой буквы чтоб пройти PR title checker

2023-10-13 05:08 UTC, idzm approved these changes

2023-10-13 05:33 UTC, idzm approved these changes

2023-10-13 05:33 UTC, merged