task_01
brstu/TMAU-2023 pull request #9
Opened 2023-09-28 22:54 UTC by sunset-ccc

2023-09-29 05:11 UTC, Aurora-hwan reviewed
Классный код, хорошо разобралась в задании!

2023-09-29 09:10 UTC, Asya2003 approved these changes
Молодец

2023-10-02 09:40 UTC, idzm requested changes
Отсутствует файл описания сборки "CMakeLists.txt".

2023-10-13 09:08 UTC, idzm approved these changes

2023-10-13 09:08 UTC, merged